apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
  namespace: atm-banking
data:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/bankdb
  REDIS_URL: redis://redis:6379/0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: atm-banking
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: thatonekap/atm-account:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: account-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: atm-banking
spec:
  selector:
    app: account
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: account-hpa
  namespace: atm-banking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
